blank_issues_enabled: false
contact_links:
  - name: 💬 Questions & ideas
    url: https://github.com/jeffrey2423/coding-standards/discussions
    about: Ask questions or discuss ideas before opening an issue.
